Repository CycloneDX/cyclonedx-python, pull requests merged in 2022-12, with the labels that each got.

#451 ci: fix py36
  .github/workflows/python.yml
Labels: CI

#452 ci: migrate `set-output` to `>> $GITHUB_OUTPUT`
  .github/workflows/docker.yml
  .github/workflows/release.yml
Labels: CI

#453 ci: test dockerimage fix
  .github/workflows/docker.yml
Labels: CI

#450 fix: adjust dependency `pip-requirements-parser` to a working version
  poetry.lock
  pyproject.toml
  requirements.lowest.txt
Labels: dependencies

#463 fix: ignore broken licenses in `environment` parser
  cyclonedx_py/parser/environment.py
Labels: bug

#465 feat: error- and debug-output is send to STDERR, instead of STDOUT
  cyclonedx_py/client.py
Labels: enhancement

#466 feat: parsers can outbut more debug messages
  .github/workflows/docker.yml
  cyclonedx_py/client.py
  cyclonedx_py/parser/_debug.py
  cyclonedx_py/parser/conda.py
  cyclonedx_py/parser/environment.py
  cyclonedx_py/parser/pipenv.py
  cyclonedx_py/parser/poetry.py
  cyclonedx_py/parser/requirements.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#469 feat: support poetry lock format 2.0
  cyclonedx_py/parser/poetry.py
  poetry.lock
  pyproject.toml
  tests/fixtures/poetry-lock11-simple.txt
  tests/fixtures/poetry-lock20-simple.txt
  tests/test_parser_poetry.py
Labels: enhancement, source: poetry

#470 docs: improve CONTRIBUTION instructions - sign-off step
  CONTRIBUTING.md
Labels: documentation

#471 fix: PURL for PyPI packages from 'conda list' have the correct format now
  cyclonedx_py/utils/conda.py
  tests/fixtures/conda-list-issue462.json
  tests/test_parser_conda.py
Labels: bug

#473 docs: fix shields
  README.md
Labels: documentation

#478 chore(deps-dev): slack version pinning of `mypy`
  poetry.lock
  pyproject.toml
Labels: dependencies, python, QA
