Repository CycloneDX/cyclonedx-python, pull requests merged in 2023-03, with the labels that each got.

#521 feat: bump `cyclonedx-python-lib` to latest RC of `4.0.x`
  .github/workflows/docker.yml
  .github/workflows/manual-release-candidate.yml
  .github/workflows/python.yml
  .github/workflows/release.yml
  cyclonedx_py/client.py
  cyclonedx_py/parser/conda.py
  cyclonedx_py/parser/environment.py
  cyclonedx_py/parser/pipenv.py
  cyclonedx_py/parser/poetry.py
  deps.lowest.r
  poetry.lock
  pyproject.toml
  tests/test_parser_environment.py
  tox.ini
Labels: dependencies, breaking change

#526 BREAKING CHANGE: remove deprecated `cyclonedx-bom` command #488
  docs/usage.rst
  pyproject.toml
Labels: breaking change

#534 Feat: omit development dependencies from SBOM results
  README.md
  cyclonedx_py/client.py
  cyclonedx_py/parser/pipenv.py
  cyclonedx_py/parser/poetry.py
  docs/usage.rst
  tests/fixtures/pipfile-lock-dev-dep.txt
  tests/fixtures/poetry-dev-dep.txt
  tests/test_parser_pipenv.py
  tests/test_parser_poetry.py
Labels: enhancement

#536 feat: use `cyclonedx-python-lib` `4.0.0`
  deps.lowest.r
  poetry.lock
  pyproject.toml
Labels: enhancement, dependencies, breaking change
