Repository CycloneDX/cyclonedx-python, pull requests merged in 2024-09, with the labels that each got.

#787 fix: assert copyright headers
  .flake8
  cyclonedx_py/__init__.py
  cyclonedx_py/__main__.py
  cyclonedx_py/_internal/__init__.py
  cyclonedx_py/_internal/cli.py
  cyclonedx_py/_internal/cli_common.py
  cyclonedx_py/_internal/environment.py
  cyclonedx_py/_internal/pipenv.py
  cyclonedx_py/_internal/poetry.py
  cyclonedx_py/_internal/requirements.py
  cyclonedx_py/_internal/utils/args.py
  cyclonedx_py/_internal/utils/cdx.py
  cyclonedx_py/_internal/utils/io.py
  cyclonedx_py/_internal/utils/license_trove_classifier.py
  cyclonedx_py/_internal/utils/mimetypes.py
  cyclonedx_py/_internal/utils/packaging.py
  cyclonedx_py/_internal/utils/pep610.py
  cyclonedx_py/_internal/utils/pep621.py
  cyclonedx_py/_internal/utils/pep639.py
  cyclonedx_py/_internal/utils/poetry.py
  cyclonedx_py/_internal/utils/pyproject.py
  cyclonedx_py/_internal/utils/secret.py
  cyclonedx_py/_internal/utils/toml.py
  pyproject.toml
  tests/__init__.py
  tests/_data/infiles/_helpers/local_pckages/a/module_a.py
  tests/_data/infiles/_helpers/local_pckages/b/module_b.py
  tests/_data/infiles/_helpers/local_pckages/c/module_c.py
  tests/_data/infiles/_helpers/pypi-proxy.py
  tests/_data/infiles/environment/editable-self/init.py
  tests/_data/infiles/environment/local/init.py
  tests/_data/infiles/environment/no-deps/init.py
  tests/_data/infiles/environment/normalize-packagename/init.py
  tests/_data/infiles/environment/private-packages/init.py
  tests/_data/infiles/environment/via-pdm/init.py
  tests/_data/infiles/environment/via-pipenv/init.py
  tests/_data/infiles/environment/via-poetry/dummy.py
  tests/_data/infiles/environment/via-poetry/init.py
  tests/_data/infiles/environment/with-extras/init.py
  tests/_data/infiles/environment/with-license-file/init.py
  tests/_data/infiles/environment/with-license-pep639/init.py
  tests/_data/infiles/environment/with-license-text/init.py
  tests/_data/infiles/environment/with-urls/init.py
  tests/functional/__init__.py
  tests/functional/test_license_trove_classifier.py
  tests/integration/__init__.py
  tests/integration/test_cli.py
  tests/integration/test_cli_environment.py
  tests/integration/test_cli_pipenv.py
  tests/integration/test_cli_poetry.py
  tests/integration/test_cli_requirements.py
  tests/unit/__init__.py
  tests/unit/test_cli.py
Labels: chore

#788 docs: reformat help page in `usage` docs
  docs/usage.rst
Labels: documentation

#790 feat: populate properties `cdx:python:package:source:vcs:...`
  cyclonedx_py/_internal/__init__.py
  cyclonedx_py/_internal/cli.py
  cyclonedx_py/_internal/environment.py
  cyclonedx_py/_internal/pipenv.py
  cyclonedx_py/_internal/poetry.py
  cyclonedx_py/_internal/requirements.py
  tests/_data/snapshots/environment/plain_with-urls_1.3.json.bin
  tests/_data/snapshots/environment/plain_with-urls_1.3.xml.bin
  tests/_data/snapshots/environment/plain_with-urls_1.4.json.bin
  tests/_data/snapshots/environment/plain_with-urls_1.4.xml.bin
  tests/_data/snapshots/environment/plain_with-urls_1.5.json.bin
  tests/_data/snapshots/environment/plain_with-urls_1.5.xml.bin
  tests/_data/snapshots/environment/plain_with-urls_1.6.json.bin
  tests/_data/snapshots/environment/plain_with-urls_1.6.xml.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.3.json.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.3.xml.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.4.json.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.4.xml.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.5.json.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.5.xml.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.6.json.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.6.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.3.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.3.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.4.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.4.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.5.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.5.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.6.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.6.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.3.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.3.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.4.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.4.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.5.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.5.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.6.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.6.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.3.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.3.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.4.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.4.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.5.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.5.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.6.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.6.xml.bin
Labels: enhancement

#795 chore: trusted publishing
  .github/workflows/release.yml
  CHANGELOG.md
  cyclonedx_py/__init__.py
  docs/conf.py
  pyproject.toml
Labels: chore

#791 feat!: drop deprecated properties `cdx:poetry:...`
  cyclonedx_py/_internal/__init__.py
  cyclonedx_py/_internal/environment.py
  cyclonedx_py/_internal/poetry.py
  tests/_data/snapshots/environment/plain_with-urls_1.3.json.bin
  tests/_data/snapshots/environment/plain_with-urls_1.3.xml.bin
  tests/_data/snapshots/environment/plain_with-urls_1.4.json.bin
  tests/_data/snapshots/environment/plain_with-urls_1.4.xml.bin
  tests/_data/snapshots/environment/plain_with-urls_1.5.json.bin
  tests/_data/snapshots/environment/plain_with-urls_1.5.xml.bin
  tests/_data/snapshots/environment/plain_with-urls_1.6.json.bin
  tests/_data/snapshots/environment/plain_with-urls_1.6.xml.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.3.json.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.3.xml.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.4.json.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.4.xml.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.5.json.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.5.xml.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.6.json.bin
  tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.6.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.3.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.3.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.4.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.4.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.5.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.5.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.6.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock10_1.6.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.3.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.3.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.4.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.4.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.5.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.5.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.6.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock11_1.6.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.3.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.3.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.4.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.4.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.5.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.5.xml.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.6.json.bin
  tests/_data/snapshots/poetry/plain_with-urls_lock20_1.6.xml.bin
Labels: enhancement, breaking change

#806 tests: consolidate cli runner
  cyclonedx_py/_internal/cli.py
  tests/integration/__init__.py
  tests/integration/test_cli.py
  tests/integration/test_cli_environment.py
  tests/integration/test_cli_pipenv.py
  tests/integration/test_cli_poetry.py
  tests/integration/test_cli_requirements.py
Labels: QA

#805 fix: help page for sub command "environment" on windows
  cyclonedx_py/_internal/environment.py
  tests/integration/test_cli.py
  tests/integration/test_cli_environment.py
  tests/integration/test_cli_pipenv.py
  tests/integration/test_cli_poetry.py
  tests/integration/test_cli_requirements.py
Labels: bug
