Repository CycloneDX/cyclonedx-python, pull requests merged in 2025-04, with the labels that each got.

#876 refactor: reorder CLI switches
  cyclonedx_py/_internal/cli.py
  docs/usage.rst
Labels: documentation

#877 docs: reword common CLI switches
  cyclonedx_py/_internal/cli.py
  cyclonedx_py/_internal/cli_common.py
  docs/usage.rst
Labels: documentation

#882 feat: support runtime-dependency `packaging ^25`
  pyproject.toml
Labels: enhancement, dependencies

#864 ci: test macos latest
  .github/workflows/python.yml
Labels: CI

#886 feat: Add mimetype detection for rich text format (rtf)
  cyclonedx_py/_internal/utils/mimetypes.py
Labels: enhancement
